In [25]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [26]:
DF = pd.read_csv("C:/Users/steff/OneDrive/Documents/Python Scripts/CHALL RS TEST.csv")

In [27]:
DF

USER_ID   CH_ID  REVIEWS_REPORT_COUNT  COMMENT_REPORT_COUNT  \
0           1    CH_1                     5                     1   
1           1    CH_2                     1                     0   
2           1    CH_3                     5                     2   
3           1    CH_4                     0                     0   
4           1    CH_5                     1                     2   
...       ...     ...                   ...                   ...   
9995      100   CH_96                     2                     0   
9996      100   CH_97                     1                     2   
9997      100   CH_98                     4                     2   
9998      100   CH_99                     5                     0   
9999      100  CH_100                     2                     1   

      FOLLOW_REPORT  SHARE_REPOR_COUNT  TO ACCEPT_REPORT  TEST VIDEO_REPORT  \
0                 0                  0                 1                  0   
1                 1                  1                 1                  0   
2                 1                  2                 0                  1   
3                 1                  1                 0                  0   
4                 1                  0                 0                  1   
...             ...                ...               ...                ...   
9995              1                  1                 1                  1   
9996              0                  1                 0                  1   
9997              1                  0                 1                  1   
9998              1                  0                 0                  0   
9999              1                  2                 0                  0   

      ALL_INTERACTIONS  UPLOADED_DAYS_ AGO  
0                    7                 365  
1                    4                 361  
2                   11                 357  
3                    2                 353  
4                    5                 349  
...                ...                 ...  
9995                 6                   1  
9996                 5                   1  
9997                 9                   1  
9998                 6                   1  
9999                 6                   1  

[10000 rows x 10 columns]

In [28]:
df = pd.read_csv("C:/Users/steff/OneDrive/Documents/Python Scripts/CHALL RS ALL_INTERACTIONS.csv")

In [29]:
df

USER_ID   CH_ID  ALL_INTERACTIONS  UPLOADED_DAYS_AGO
0           1    CH_1                 7                365
1           1    CH_2                 4                361
2           1    CH_3                11                357
3           1    CH_4                 2                353
4           1    CH_5                 5                349
...       ...     ...               ...                ...
9995      100   CH_96                 6                  1
9996      100   CH_97                 5                  1
9997      100   CH_98                 9                  1
9998      100   CH_99                 6                  1
9999      100  CH_100                 6                  1

[10000 rows x 4 columns]

In [33]:
m7= df.pivot_table(index=["USER_ID"], columns=["CH_ID"], values=["ALL_INTERACTIONS"])

In [35]:
m7.head(10)

ALL_INTERACTIONS                                                   \
CH_ID               CH_1 CH_10 CH_100 CH_11 CH_12 CH_13 CH_14 CH_15 CH_16   
USER_ID                                                                     
1                      7     7      9     5     6     4     3     7     7   
2                      7     8     10     9    10     5    11     8     7   
3                      6     7      6     4     5     6     4     5     7   
4                     10    10      3     8     5     7     5     9     7   
5                      8     7      3     6     5     2     9     6     7   
6                      2     7      4     5     7     7     2     4     8   
7                      9     8      6     8     5     8     3     4     8   
8                     10     4      9     7     6    10     8     1     6   
9                      9     7      7     6     3     4     8     3     6   
10                     6     7     10     6     7     3     5     6     9   

               ...                                                              
CH_ID   CH_17  ... CH_90 CH_91 CH_92 CH_93 CH_94 CH_95 CH_96 CH_97 CH_98 CH_99  
USER_ID        ...                                                              
1           7  ...     4     5     5     6     9     7     5     4     9     8  
2           7  ...     4     3    10     4     2     2     7     9     7     7  
3           8  ...     9     5     1     3     9     7     5     7     5     4  
4           7  ...     8     4     6     7    10     6     8     5     6     1  
5           5  ...     3     5     3     4     7     5     4     5     7     6  
6           6  ...     8    10     5    10     4     3     7     9     4     6  
7          10  ...     2     6     4     5     7     8     7     6     8     7  
8           4  ...     7     4     6     5     8     3     2     5     4     8  
9           7  ...     3     8     3     8     5     6     5     7     6     4  
10          5  ...     4     2     2     7    10     5     6     3     6     8  

[10 rows x 100 columns]

In [36]:
m7_T = m7.values.T
m7_T.shape
#Fitting the Model
SVD = TruncatedSVD(n_components=5, random_state=0)#are five category
matrix = SVD.fit_transform(m7_T)
matrix.shape 

(100, 5)

In [37]:
m7_T

array([[ 7,  7,  6, ...,  8,  5,  6],
       [ 7,  8,  7, ...,  8,  4,  7],
       [ 9, 10,  6, ...,  4,  4,  6],
       ...,
       [ 4,  9,  7, ...,  7,  6,  5],
       [ 9,  7,  5, ...,  6,  6,  9],
       [ 8,  7,  4, ...,  6,  3,  6]], dtype=int64)

In [43]:
import warnings
warnings.filterwarnings("ignore",category =RuntimeWarning)
Sim = np.corrcoef(matrix)

In [44]:
Sim.shape

(100, 100)

In [45]:
Sim

array([[1.        , 0.99872597, 0.96846351, ..., 0.98134994, 0.96939524,
        0.9926494 ],
       [0.99872597, 1.        , 0.95744107, ..., 0.97620486, 0.96603445,
        0.98725137],
       [0.96846351, 0.95744107, 1.        , ..., 0.98803273, 0.97785008,
        0.97467087],
       ...,
       [0.98134994, 0.97620486, 0.98803273, ..., 1.        , 0.99714516,
        0.98683941],
       [0.96939524, 0.96603445, 0.97785008, ..., 0.99714516, 1.        ,
        0.97473526],
       [0.9926494 , 0.98725137, 0.97467087, ..., 0.98683941, 0.97473526,
        1.        ]])

In [73]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


In [74]:
V, s, U = svd(Sim)

In [75]:
V

array([[-1.00185000e-01, -1.24725061e-01,  4.37062663e-02, ...,
         1.55594353e-01, -2.27028122e-01,  1.46626053e-01],
       [-1.00043055e-01, -1.60640744e-01,  2.35112784e-02, ...,
         1.06551428e-01,  7.91810989e-02, -8.38309964e-02],
       [-9.89554582e-02,  1.77085261e-01,  8.67320553e-02, ...,
         2.81867343e-03,  1.45309531e-02,  1.99043240e-02],
       ...,
       [-1.00235903e-01,  8.56122192e-02, -7.94492050e-02, ...,
        -6.14128716e-02,  1.00301366e-02, -3.28147775e-02],
       [-9.97205102e-02,  1.17515298e-01, -1.53918298e-01, ...,
        -1.79389881e-04,  6.22383141e-02,  6.37943648e-02],
       [-9.94153639e-02, -7.73002403e-02, -2.78106445e-02, ...,
        -1.69502232e-01,  7.32486942e-02, -8.94633426e-02]])

In [80]:
s

array([9.81985673e+01, 6.38553757e-01, 5.85404069e-01, 5.77474826e-01,
       5.60953182e-14, 4.82470114e-14, 3.89946534e-14, 3.28588881e-14,
       3.12346799e-14, 2.76796240e-14, 2.26526697e-14, 2.23359362e-14,
       1.87581704e-14, 1.37441976e-14, 9.76218317e-15, 9.76218317e-15,
       9.76218317e-15, 9.76218317e-15, 9.76218317e-15, 9.76218317e-15,
       9.76218317e-15, 9.76218317e-15, 9.76218317e-15, 9.76218317e-15,
       9.76218317e-15, 9.76218317e-15, 9.76218317e-15, 9.76218317e-15,
       9.76218317e-15, 9.76218317e-15, 9.76218317e-15, 9.76218317e-15,
       9.76218317e-15, 9.76218317e-15, 9.76218317e-15, 9.76218317e-15,
       9.76218317e-15, 9.76218317e-15, 9.76218317e-15, 9.76218317e-15,
       9.76218317e-15, 9.76218317e-15, 9.76218317e-15, 9.76218317e-15,
       9.76218317e-15, 9.76218317e-15, 9.76218317e-15, 9.76218317e-15,
       9.76218317e-15, 9.76218317e-15, 9.76218317e-15, 9.76218317e-15,
       9.76218317e-15, 9.76218317e-15, 9.76218317e-15, 9.76218317e-15,
      

In [81]:
V = matrix(V)

In [82]:
V

matrix([[-1.00185000e-01, -1.24725061e-01,  4.37062663e-02, ...,
          1.55594353e-01, -2.27028122e-01,  1.46626053e-01],
        [-1.00043055e-01, -1.60640744e-01,  2.35112784e-02, ...,
          1.06551428e-01,  7.91810989e-02, -8.38309964e-02],
        [-9.89554582e-02,  1.77085261e-01,  8.67320553e-02, ...,
          2.81867343e-03,  1.45309531e-02,  1.99043240e-02],
        ...,
        [-1.00235903e-01,  8.56122192e-02, -7.94492050e-02, ...,
         -6.14128716e-02,  1.00301366e-02, -3.28147775e-02],
        [-9.97205102e-02,  1.17515298e-01, -1.53918298e-01, ...,
         -1.79389881e-04,  6.22383141e-02,  6.37943648e-02],
        [-9.94153639e-02, -7.73002403e-02, -2.78106445e-02, ...,
         -1.69502232e-01,  7.32486942e-02, -8.94633426e-02]])

In [83]:
U= matrix(U)

In [84]:
U

matrix([[-1.00185000e-01, -1.00043055e-01, -9.89554582e-02, ...,
         -1.00235903e-01, -9.97205102e-02, -9.94153639e-02],
        [-1.24725061e-01, -1.60640744e-01,  1.77085261e-01, ...,
          8.56122192e-02,  1.17515298e-01, -7.73002403e-02],
        [ 4.37062663e-02,  2.35112784e-02,  8.67320553e-02, ...,
         -7.94492050e-02, -1.53918298e-01, -2.78106445e-02],
        ...,
        [ 0.00000000e+00,  3.31877869e-02,  2.57223621e-01, ...,
         -6.86200601e-03,  3.72704415e-02, -2.14765706e-03],
        [ 3.25559121e-01,  3.18808530e-03,  7.77166697e-02, ...,
         -1.78727074e-02, -3.97266445e-02,  9.71431662e-02],
        [-8.99930078e-01, -8.10631022e-02,  7.71197081e-02, ...,
          6.46356214e-04, -2.26666179e-02,  7.83957313e-02]])

In [85]:
U[:2]

matrix([[-0.100185  , -0.10004306, -0.09895546, -0.09970416, -0.10005763,
         -0.09927903, -0.10049102, -0.10020363, -0.10073324, -0.10028985,
         -0.09964942, -0.10042857, -0.09983155, -0.10038526, -0.10068215,
         -0.10021096, -0.09903063, -0.10074262, -0.09809825, -0.09960643,
         -0.10060401, -0.0986668 , -0.10017578, -0.10034407, -0.10012958,
         -0.09995977, -0.09994272, -0.09819879, -0.10085976, -0.09824493,
         -0.10068865, -0.09931477, -0.09983782, -0.10076327, -0.09997384,
         -0.09999138, -0.10020396, -0.09893994, -0.10056536, -0.10077424,
         -0.10011413, -0.10048691, -0.09967466, -0.09944084, -0.10073727,
         -0.10027804, -0.10064587, -0.10061843, -0.10023951, -0.09999892,
         -0.10078971, -0.1004423 , -0.09998384, -0.10014591, -0.10061074,
         -0.10082681, -0.09887425, -0.09975572, -0.09858586, -0.10087666,
         -0.09997358, -0.10006485, -0.09764395, -0.10069416, -0.10050548,
         -0.10068698, -0.10060718, -0.

In [86]:
V[:,:2]

matrix([[-0.100185  , -0.12472506],
        [-0.10004306, -0.16064074],
        [-0.09895546,  0.17708526],
        [-0.09970416,  0.18364395],
        [-0.10005763,  0.10924746],
        [-0.09927903,  0.08422796],
        [-0.10049102, -0.09275755],
        [-0.10020363,  0.0586599 ],
        [-0.10073324, -0.04472458],
        [-0.10028985, -0.07840793],
        [-0.09964942,  0.19288656],
        [-0.10042857, -0.09512695],
        [-0.09983155, -0.1562234 ],
        [-0.10038526,  0.00790601],
        [-0.10068215, -0.04867972],
        [-0.10021096,  0.11340895],
        [-0.09903063, -0.19877034],
        [-0.10074262,  0.0572828 ],
        [-0.09809825,  0.16066992],
        [-0.09960643,  0.12243454],
        [-0.10060401, -0.01858332],
        [-0.0986668 , -0.10673931],
        [-0.10017578,  0.13841807],
        [-0.10034407,  0.05216254],
        [-0.10012958,  0.01646912],
        [-0.09995977, -0.09614641],
        [-0.09994272,  0.05470869],
        [-0.09819879,  0.055

In [93]:
diag(s[:3]) #estos serán los valores absolutos por cada categoría e challenges

array([[98.19856735,  0.        ,  0.        ],
       [ 0.        ,  0.63855376,  0.        ],
       [ 0.        ,  0.        ,  0.58540407]])

In [94]:
Sim=matrix(Sim)

In [95]:
Sim

matrix([[1.        , 0.99872597, 0.96846351, ..., 0.98134994, 0.96939524,
         0.9926494 ],
        [0.99872597, 1.        , 0.95744107, ..., 0.97620486, 0.96603445,
         0.98725137],
        [0.96846351, 0.95744107, 1.        , ..., 0.98803273, 0.97785008,
         0.97467087],
        ...,
        [0.98134994, 0.97620486, 0.98803273, ..., 1.        , 0.99714516,
         0.98683941],
        [0.96939524, 0.96603445, 0.97785008, ..., 0.99714516, 1.        ,
         0.97473526],
        [0.9926494 , 0.98725137, 0.97467087, ..., 0.98683941, 0.97473526,
         1.        ]])

In [98]:
V[:,:2]* diag(s[:2])* U[:2]# multiplicatión

matrix([[0.99555593, 0.99701994, 0.9594224 , ..., 0.97930469, 0.97169337,
         0.98420715],
        [0.99701994, 0.99930961, 0.9539818 , ..., 0.97594409, 0.96760828,
         0.98459424],
        [0.9594224 , 0.9539818 , 0.98160284, ..., 0.98370165, 0.98230099,
         0.95730636],
        ...,
        [0.97930469, 0.97594409, 0.98370165, ..., 0.99130445, 0.98797551,
         0.97432177],
        [0.97169337, 0.96760828, 0.98230099, ..., 0.98797551, 0.98532257,
         0.96771553],
        [0.98420715, 0.98459424, 0.95730636, ..., 0.97432177, 0.96771553,
         0.97435272]])